root: true

env:
  es6: true

plugins:
  - "svelte3"
  - "@typescript-eslint"

overrides:
  - files:
      - "*.svelte"
    processor: "svelte3/svelte3"

parser: "@typescript-eslint/parser"

settings:
  svelte3/typescript: true

parserOptions:
  ecmaVersion: 2018
  impliedStrict: true
  sourceType: module
  project: ./**/tsconfig.json

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
