root: true

env:
  node: true

plugins:
  - "@typescript-eslint"

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2018
  impliedStrict: true
  sourceType: module
  project: ./tsconfig.json

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"

rules:
  '@typescript-eslint/no-empty-interface': 0
