import express from "express";
import cors from "cors";
import * as path from "path";
import { connectDatabase } from "./database/database";
// import { SignatureModel } from "./models/signature.model";
// import { EventModel } from "./models/event.model";
// import { ResultModel } from "./models/result.model";
import { CompetitorModel } from "./models/competitor.model";
// import { CompetitionModel } from "./models/competition.model";

connectDatabase();

const app = express();
const port = process.env.PORT || 5001;

app.get("*", async (_, res) =>
  res.sendFile(path.resolve(__dirname, "../public", "index.html"))
);

app.use(cors());
app.use(express.static("../public"));

app.listen(port, () => console.log(`Server is up at port ${port}`));
// const competitor = {
//   "_id": "60fc0b0f06ae5258a455c321",
//   "ageGroup": "",
//   "checkedIn": false,
//   "competitorId": "10",
//   "dateOfBirth": "1993-06-13",
//   "event": "T05",
//   "firstName": "MITKO",
//   "flagUrl": "//files.opentrack.run/live/countryflags/ioc/BUL.svg",
//   "gender": "M",
//   "lastName": "TSENOV",
//   "nonScorer": false,
//   "numbered": false,
//   "otAthleteId": "57a24e39-147f-44ac-b3df-d9d63d8a3120",
//   "sortAgeGroup": "3-",
//   "teamName": "",
//   "pb": "3:44.86",
//   "age": "28",
//   "competitionId": "60fc0b0f06ae5258a455c31e",
//   "sortBib": 10,
//   "teamId": "BUL",
//   "__v": 0
// }

// console.log("CompetitorModel.findCompetitorByBib() ", CompetitorModel.createCompetitor("60fc0b0f06ae5258a455c31e", competitor));

console.log("CompetitorModel.findCompetitorByBib() ", CompetitorModel.findCompetitorByBib(101));

// const competition = {
//   "_id" : "60fc0b0f06ae5258a455c31e",
//   "country" : "SRB",
//   "date" : "2021-02-24",
//   "finishDate" : "2021-02-24",
//   "fullName" : "Bronze - Serbian Open Indoor Meeting 2021",
//   "id" : "aa0af858-cff0-4e48-bd6a-5139cd43c813",
//   "organiser" : "b89377e7-ec18-4ec5-9c5b-e87d2b649c39",
//   "scoringSystem" : "",
//   "shortName" : "SOIM 2021.",
//   "slug" : "srbopenindoor",
//   "teamTypes" : "NATIONAL",
//   "type" : "INDOOR",
//   "year" : 2021,
//   "address" : "Булевар Ослобођења 54 Београд, Србија",
//   "basicDescription" : "",
//   "contactDetails" : "takmicenja@serbia-athletics.org.ra",
//   "englishName" : "Serbian Open Indoor Meeting 2021",
//   "latitude" : 44.7748,
//   "longitude" : 20.4736,
//   "resultsLink" : "",
//   "__v" : 0
// }
// console.log("CompetitionModel.findCompetitionById() ", CompetitionModel.findCompetitionById("6102e0d1619d30245cb71cc6"));
// console.log("CompetitionModel.createCompetition() ", CompetitionModel.createCompetition(competition));


// console.log("SignatureModel.createNewSignature ", SignatureModel.createNewSignature({
//   name: "Emma",
//   title: "Bradley"
// }));

// console.log("SignatureModel.createNewSignature ", SignatureModel.createNewSignature({
//   name: "Berda",
//   title: "Car"
// }));

// console.log("SignatureModel.getSignatures ", SignatureModel.getSignatures());
// const event = {
//   "ageGroups": [
//     "SEN",
//     "U18",
//     "U20"
//   ],
//   "cachedCount": 6.0,
//   "category": "seniorke",
//   "ceScoreFormula": "x",
//   "cutAfterRound": 3.0,
//   "cutSurvivors": 8.0,
//   "day": 1.0,
//   "eventCode": "HJ",
//   "eventId": "F01",
//   "genders": "F",
//   "heatTimeCalculation": "AUTO",
//   "lanes": 8.0,
//   "maxFieldAttempts": 6.0,
//   "name": "skok uvis - Ž",
//   "r1Time": "17:55",
//   "r2Day": 1.0,
//   "r3Day": 1.0,
//   "reorderLastRound": false,
//   "requireCallroomOverride": false,
//   "rounds": "1",
//   "seedingMethod": "",
//   "status": "complete",
//   "teamTypes": "INHERIT",
//   "note": "",
//   "__v": 0.0
// }
// console.log("EventModel.createEvent ", EventModel.createEvent("Marko", event));
// console.log("EventModel.getEvents ",EventModel.getEvents());
// console.log("EventModel.editEvent ", EventModel.editEvent("6103007486b4c85c322106d2", "Car", "vreme", "note"));
// const basicData = {
//   day: 1,
//   event_id: 'F04',
//   event_name: 'skok udalj - M',
//   heat: 1,
//   heat_name: 'F04 skok udalj - M',
//   override_ce_scores: false,
//   override_places: false,
//   results: [
//     {
//       advancement: '',
//       age_group: '',
//       athlon_points: '',
//       bib: '18',
//       category: '',
//       catpos: 7,
//       date_of_birth: '2001-08-05',
//       extra_url: '',
//       first_name: 'MARKO',
//       first_name_local: '',
//       flag: '//files.opentrack.run/live/countryflags/ioc/MLZ.svg',
//       gender: 'M',
//       last_name: 'VLAHOVIĆ',
//       last_name_local: '',
//       needs_review: '',
//       note: '',
//       order: 1,
//       pb: null,
//       performance: '7.10',
//       place: 7,
//       points: 0,
//       qp: '7.19',
//       sb: '7.19',
//       team: 'MLZ',
//       team_category: '',
//       weight: '',
//       wind: ''
//     },
//     {
//       advancement: '',
//       age_group: '',
//       athlon_points: '',
//       bib: '16',
//       category: '',
//       catpos: 3,
//       date_of_birth: '2000-03-08',
//       extra_url: '',
//       first_name: 'MARKO',
//       first_name_local: '',
//       flag: '//files.opentrack.run/live/countryflags/ioc/CRO.svg',
//       gender: 'M',
//       last_name: 'ČEKO',
//       last_name_local: '',
//       needs_review: '',
//       note: '',
//       order: 2,
//       pb: '7.78',
//       performance: '7.73',
//       place: 3,
//       points: 0,
//       qp: '7.77',
//       sb: '7.77',
//       team: 'CRO',
//       team_category: '',
//       weight: '',
//       wind: ''
//     },
//     {
//       advancement: '',
//       age_group: '',
//       athlon_points: '',
//       bib: '17',
//       category: '',
//       catpos: 1,
//       date_of_birth: '1991-12-14',
//       extra_url: '',
//       first_name: 'LAZAR',
//       first_name_local: '',
//       flag: '//files.opentrack.run/live/countryflags/ioc/RKG.svg',
//       gender: 'M',
//       last_name: 'ANIĆ',
//       last_name_local: '',
//       needs_review: '',
//       note: '',
//       order: 3,
//       pb: '7.98',
//       performance: '7.91',
//       place: 2,
//       points: 0,
//       qp: '7.70',
//       sb: '7.70',
//       team: 'RKG',
//       team_category: '',
//       weight: '',
//       wind: ''
//     },
//     {
//       advancement: '',
//       age_group: '',
//       athlon_points: '',
//       bib: '14',
//       category: '',
//       catpos: 2,
//       date_of_birth: '1999-03-29',
//       extra_url: '',
//       first_name: 'IZMIR',
//       first_name_local: '',
//       flag: '//files.opentrack.run/live/countryflags/ioc/ALB.svg',
//       gender: 'M',
//       last_name: 'SMAJLAJ',
//       last_name_local: '',
//       needs_review: '',
//       note: '',
//       order: 4,
//       pb: '8.11',
//       performance: '7.91',
//       place: 1,
//       points: 0,
//       qp: '7.91',
//       sb: '7.91',
//       team: 'ALB',
//       team_category: '',
//       weight: '',
//       wind: ''
//     },
//     {
//       advancement: '',
//       age_group: '',
//       athlon_points: '',
//       bib: '13',
//       category: '',
//       catpos: 6,
//       date_of_birth: '1994-03-02',
//       extra_url: '',
//       first_name: 'YANN',
//       first_name_local: '',
//       flag: '//files.opentrack.run/live/countryflags/ioc/FRA.svg',
//       gender: 'M',
//       last_name: 'RANDRIANASOLO',
//       last_name_local: '',
//       needs_review: '',
//       note: '',
//       order: 5,
//       pb: '7.94',
//       performance: '7.61',
//       place: 6,
//       points: 0,
//       qp: '7.82',
//       sb: '7.82',
//       team: 'FRA',
//       team_category: '',
//       weight: '',
//       wind: ''
//     },
//     {
//       advancement: '',
//       age_group: '',
//       athlon_points: '',
//       bib: '15',
//       category: '',
//       catpos: 4,
//       date_of_birth: '2000-07-24',
//       extra_url: '',
//       first_name: 'BORIS',
//       first_name_local: '',
//       flag: '//files.opentrack.run/live/countryflags/ioc/BUL.svg',
//       gender: 'M',
//       last_name: 'LINKOV',
//       last_name_local: '',
//       needs_review: '',
//       note: '',
//       order: 6,
//       pb: '7.85',
//       performance: '7.70',
//       place: 4,
//       points: 0,
//       qp: '7.85',
//       sb: '7.85',
//       team: 'BUL',
//       team_category: '',
//       weight: '',
//       wind: ''
//     },
//     {
//       advancement: '',
//       age_group: '',
//       athlon_points: '',
//       bib: '12',
//       category: '',
//       catpos: 5,
//       date_of_birth: '1999-08-25',
//       extra_url: '',
//       first_name: 'PANAGIOTIS',
//       first_name_local: '',
//       flag: '//files.opentrack.run/live/countryflags/ioc/GRE.svg',
//       gender: 'M',
//       last_name: 'MANTZOUROGIANNIS',
//       last_name_local: '',
//       needs_review: '',
//       note: '',
//       order: 7,
//       pb: '7.69',
//       performance: '7.62',
//       place: 5,
//       points: 0,
//       qp: '7.62',
//       sb: '7.62',
//       team: 'GRE',
//       team_category: '',
//       weight: '',
//       wind: ''
//     },
//     {
//       advancement: '',
//       age_group: '',
//       athlon_points: '',
//       bib: '11',
//       category: '',
//       catpos: 8,
//       date_of_birth: '2002-02-06',
//       extra_url: '',
//       first_name: 'PETAR',
//       first_name_local: '',
//       flag: '//files.opentrack.run/live/countryflags/ioc/VNS.svg',
//       gender: 'M',
//       last_name: 'ČANAK',
//       last_name_local: '',
//       needs_review: '',
//       note: '',
//       order: 8,
//       pb: null,
//       performance: '7.02',
//       place: 8,
//       points: 0,
//       qp: '7.09',
//       sb: '7.09',
//       team: 'VNS',
//       team_category: '',
//       weight: '',
//       wind: ''
//     }
//   ],
//   results_status: 'official',
//   round: 1,
//   round_name: '',
//   rounds: 6,
//   show_athlete_details: true,
//   show_partials: true,
//   show_points: false,
//   status: 'finished',
//   trials: [
//     { bib: '18', result: '7.10', round: 1 },
//     { bib: '18', result: 'x', round: 2 },
//     { bib: '18', result: 'x', round: 3 },
//     { bib: '18', result: '6.63', round: 4 },
//     { bib: '18', result: 'x', round: 5 },
//     { bib: '18', result: 'x', round: 6 },
//     { bib: '16', result: '7.42', round: 1 },
//     { bib: '16', result: 'x', round: 2 },
//     { bib: '16', result: 'x', round: 3 },
//     { bib: '16', result: '7.73', round: 4 },
//     { bib: '16', result: '7.62', round: 5 },
//     { bib: '16', result: 'x', round: 6 },
//     { bib: '17', result: '7.65', round: 1 },
//     { bib: '17', result: '7.72', round: 2 },
//     { bib: '17', result: '7.91', round: 3 },
//     { bib: '17', result: '7.84', round: 4 },
//     { bib: '17', result: '7.84', round: 5 },
//     { bib: '17', result: 'x', round: 6 },
//     { bib: '14', result: '7.60', round: 1 },
//     { bib: '14', result: '7.76', round: 2 },
//     { bib: '14', result: '7.80', round: 3 },
//     { bib: '14', result: '7.91', round: 4 },
//     { bib: '14', result: '7.85', round: 5 },
//     { bib: '14', result: 'x', round: 6 },
//     { bib: '13', result: '5.46', round: 1 },
//     { bib: '13', result: '7.12', round: 2 },
//     { bib: '13', result: '7.37', round: 3 },
//     { bib: '13', result: '7.25', round: 4 },
//     { bib: '13', result: '7.34', round: 5 },
//     { bib: '13', result: '7.61', round: 6 },
//     { bib: '15', result: '7.49', round: 1 },
//     { bib: '15', result: '7.40', round: 2 },
//     { bib: '15', result: '7.40', round: 3 },
//     { bib: '15', result: '7.70', round: 4 },
//     { bib: '15', result: 'x', round: 5 },
//     { bib: '15', result: '7.39', round: 6 },
//     { bib: '12', result: '7.31', round: 1 },
//     { bib: '12', result: 'x', round: 2 },
//     { bib: '12', result: 'x', round: 3 },
//     { bib: '12', result: '7.33', round: 4 },
//     { bib: '12', result: '7.54', round: 5 },
//     { bib: '12', result: '7.62', round: 6 },
//     { bib: '11', result: 'x', round: 1 },
//     { bib: '11', result: '7.02', round: 2 },
//     { bib: '11', result: '6.78', round: 3 },
//     { bib: '11', result: '6.74', round: 4 },
//     { bib: '11', result: '6.82', round: 5 },
//     { bib: '11', result: '6.90', round: 6 }
//   ],
//   unit_code: ''
// };

// const result = {
//   advancement: '',
//   age_group: '',
//   athlon_points: '',
//   bib: '18',
//   category: '',
//   catpos: 7,
//   date_of_birth: '2001-08-05',
//   extra_url: '',
//   first_name: 'MARKO',
//   first_name_local: '',
//   flag: '//files.opentrack.run/live/countryflags/ioc/MLZ.svg',
//   gender: 'M',
//   last_name: 'VLAHOVIĆ',
//   last_name_local: '',
//   needs_review: '',
//   note: '',
//   order: 1,
//   pb: null,
//   performance: '7.10',
//   place: 7,
//   points: 0,
//   qp: '7.19',
//   sb: '7.19',
//   team: 'MLZ',
//   team_category: '',
//   weight: '',
//   wind: ''
// };

// console.log("ResultModel.createResult ", ResultModel.createResult(basicData, result));
// console.log("ResultModel.getResults ", ResultModel.getResults());
// console.log("ResultModel.getResults ", ResultModel.getResultsByEventId("F04"));
