name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  analyze_frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        node-version: [15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Installing Dependencies
        run: npm install

      - name: Running lint
        run: npm run lint --if-present

      - name: Building
        run: npm run build --if-present

  analyze_backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        node-version: [15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Installing Dependencies
        run: npm install

      - name: Running lint
        run: npm run lint --if-present

      - name: Building
        run: npm run build --if-present
