name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  analyze_frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

        name: Installing Dependencies on FE
        working-directory: ./
      - run: npm install
        name: Running lint on FE
        working-directory: ./
      - run: npm run lint --if-present
        name: Building FE project
        working-directory: ./
      - run: npm run build --if-present

  analyze_backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        node-version: [15.x]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

        name: Installing Dependencies on BE
        working-directory: ./backend
      - run: npm install
        name: Running lint on BE
        working-directory: ./backend
      - run: npm run lint --if-present
        name: Building BE project
        working-directory: ./backend
      - run: npm run build --if-present
