name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing Dependencies on FE
        run: npm install
      - name: Running lint on FE
        run: npm run lint --if-present
      - name: Building FE project
        run: npm run build --if-present
      - name: Installing Dependencies on BE
        working-directory: ./backend
        run: npm install
      - name: Running lint on BE
        working-directory: ./backend
        run: npm run lint --if-present
      - name: Building BE project
        working-directory: ./backend
        run: npm run build --if-present
