name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # FE tasks
        name: Installing Dependencies on FE
        working-directory: ./
      - run: npm install
        name: Running lint on FE
        working-directory: ./
      - run: npm run lint --if-present
        name: Building FE project
        working-directory: ./
      - run: npm run build --if-present

      # BE tasks
        name: Installing Dependencies on BE
        working-directory: ./backend
      - run: npm install
        name: Running lint on BE
        working-directory: ./backend
      - run: npm run lint --if-present
        name: Building BE project
        working-directory: ./backend
      - run: npm run build --if-present
